[package]
name = "fractal_mandelbrot_of_mandelbrot"
version = "0.1.0"
edition = "2024"
authors = ["lukas"]
keywords = ["fractal", "mandelbrot"]

[dependencies]
rusty_fractals = { path = "../rusty_fractals" }
