[package]
name = "fractal_collatz_mandelbrot"
version = "0.1.0"
edition = "2024"
authors = ["lukas"]
keywords = ["fractal", "collatz_conjecture"]

[dependencies]
rusty_fractals = { path = "../rusty_fractals" }
